# Generated by Django 5.0.4 on 2024-05-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=50)),
                ("telefono", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("puesto", models.CharField(max_length=50)),
                ("salario", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=50)),
                ("telefono", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                (
                    "nombreEmpleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appweb.empleados",
                    ),
                ),
            ],
        ),
    ]
